### ISSUE TITLE
HTML Entity Encoding

### ISSUE THREAD

**Issue by elguitarraverde** [Roskus/prospect-flow-crm#105]
https://github.com/Roskus/prospect-flow-crm/blob/7b7fefe58f1228be322f518e281109cebfa9ff21/app/Providers/AppServiceProvider.php#L28-L30

I think we should remove `Blade::withDoubleEncoding();` as it could pose a security problem.

we could use double braces `{{ }}` normally to perform double HTML encoding and only in controlled cases we need to use `{!! !!}`(as for example in the rendering of html by ckeditor or in the emails).

https://laravel.com/docs/10.x/blade#html-entity-encoding

**Comment by gnovaro** [comment]
Sounds a good catch i didn't remember why do that...
