### ISSUE TITLE
Notification email

### ISSUE THREAD

**Issue by gnovaro** [Roskus/prospect-flow-crm#137]
Check why this command dont send the notification email
app/Console/Commands/ScheduleNotificationReminder.php

Log error on sentry

**Comment by elguitarraverde** [comment]
@gnovaro can you show the error logs?

**Comment by elguitarraverde** [comment]
https://github.com/Roskus/prospect-flow-crm/blob/1bfda159091c28e11ef31303bd545d3d83129569/app/Console/Commands/ScheduleNotificationReminder.php#L77-L82

At the moment without having any logs, it could be that this line is found in error

change `Mail::to($recipient->seller()->email)->send($emailTemplate);` to `Mail::to($recipient->seller->email)->send($emailTemplate); `
