### ISSUE TITLE
Fix security issue

### ISSUE THREAD

**Issue by gnovaro** [Roskus/prospect-flow-crm#140]
https://github.com/Roskus/prospect-flow-crm/security/dependabot/14

Upgrade notes
https://github.com/firebase/php-jwt/releases/tag/v6.0.0

**Comment by elguitarraverde** [comment]
@gnovaro this package is installed because it is required by shopify/shopify-api, is this package being used in the crm?? I'm saying this in case we can remove shopify/shopify-api. I have eliminated it and I have passed the tests and they have all passed.
